// constants/mockData.ts

export const SITE_NAME = "Imuhira";

export const NAV_LINKS = [
  { name: "History", href: "/category/history" },
  { name: "Culture", href: "/category/culture" },
  { name: "Conflict", href: "/category/conflict" },
  { name: "Stories", href: "/category/stories" },
];


export const FEATURED_ARTICLE = {
  id: 1,
  title: "The Banyamulenge: A People's History of Resilience and Conflict",
  slug: "banyamulenge-history-resilience-conflict",
  href: "/articles/banyamulenge-history-resilience-conflict",
  excerpt: "An in-depth look at the history of the Banyamulenge people, from their pastoralist traditions to their current struggle for survival and recognition in the highlands of South Kivu.",
  main_image_url: "https://picsum.photos/seed/banyamulenge-culture/1200/600",
  author_name: "Imuhira Staff",
  published_at: "Jan 1, 2026",
  category: { name: "History", href: "/category/history" },
  youtube_video_id: "dQw4w9WgXcQ",
};

export const TRENDING_ARTICLES = [
  { 
    id: 2, 
    title: "Twirwaneho and the M23: A Controversial Alliance", 
    slug: "twirwaneho-m23-alliance",
    href: "/articles/twirwaneho-m23-alliance",
    excerpt: "The Twirwaneho militia has reportedly formed an alliance with the M23 rebels, a move that has been met with both support and condemnation.",
    main_image_url: "https://picsum.photos/seed/m23-alliance/800/600",
    category: { name: "Conflict", href: "/category/conflict" },
    author_name: "Imuhira Staff",
    published_at: "Jan 2, 2026",
    youtube_video_id: "dQw4w9WgXcQ",
  },
  { 
    id: 3, 
    title: "The 'Akagara' Perspective: Voices from within the Pro-Government Faction", 
    slug: "akagara-pro-government-perspective",
    href: "/articles/akagara-pro-government-perspective",
    excerpt: "A deep dive into the motivations and goals of the 'Akagara' faction, which advocates for cooperation with the Congolese government.",
    main_image_url: "https://picsum.photos/seed/akagara-perspective/800/600",
    category: { name: "Politics", href: "/category/politics" },
    author_name: "Imuhira Staff",
    published_at: "Jan 3, 2026",
    youtube_video_id: "dQw4w9WgXcQ",
  },
  { 
    id: 4, 
    title: "Displaced and Forgotten: The Humanitarian Crisis in Minembwe", 
    slug: "minembwe-humanitarian-crisis",
    href: "/articles/minembwe-humanitarian-crisis",
    excerpt: "Thousands of people have been displaced by the conflict in Minembwe, and the humanitarian situation is dire. This article sheds light on their plight.",
    main_image_url: "https://picsum.photos/seed/minembwe-crisis/800/600",
    category: { name: "Humanitarian", href: "/category/humanitarian" },
    author_name: "Imuhira Staff",
    published_at: "Jan 4, 2026",
    youtube_video_id: "dQw4w9WgXcQ",
  },
  { 
    id: 5, 
    title: "The 'Idubu' Narrative: Self-Defense or Rebellion?", 
    slug: "idubu-self-defense-rebellion",
    href: "/articles/idubu-self-defense-rebellion",
    excerpt: "The 'Idubu' faction, which supports the Twirwaneho militia, claims to be acting in self-defense. But is there more to their story?",
    main_image_url: "https://picsum.photos/seed/idubu-narrative/800/600",
    category: { name: "Conflict", href: "/category/conflict" },
    author_name: "Imuhira Staff",
    published_at: "Jan 5, 2026",
    youtube_video_id: "dQw4w9WgXcQ",
  },
];

export const LATEST_ARTICLES = [
  // HISTORY
  {
    id: 101,
    title: "The Banyamulenge in the Congo Wars: A Story of Shifting Alliances",
    slug: "banyamulenge-congo-wars-alliances",
    href: "/articles/banyamulenge-congo-wars-alliances",
    excerpt: "From the First Congo War to the present day, the Banyamulenge have been both victims and actors in the conflicts that have ravaged the region. This article explores their complex and often misunderstood role.",
    main_image_url: "https://picsum.photos/seed/congo-war/800/600",
    category: { name: "History", href: "/category/history" },
    author_name: "Imuhira Staff",
    published_at: "2 hours ago",
    youtube_video_id: "dQw4w9WgXcQ",
  },
  {
    id: 102,
    title: "Who Are the Banyamulenge? Debunking the Myths",
    slug: "who-are-the-banyamulenge-myths",
    href: "/articles/who-are-the-banyamulenge-myths",
    excerpt: "Are they Congolese or Rwandan? This article delves into the history of the Banyamulenge people and the origins of the controversy surrounding their identity.",
    main_image_url: "https://picsum.photos/seed/banyamulenge-identity/800/600",
    category: { name: "History", href: "/category/history" },
    author_name: "Imuhira Staff",
    published_at: "5 hours ago",
    youtube_video_id: "dQw4w9WgXcQ",
  },

  // CONFLICT
  {
    id: 201,
    title: "The 'Idubu' vs. 'Akagara' Divide: A New Fault Line in the Banyamulenge Community",
    slug: "idubu-akagara-divide-banyamulenge",
    href: "/articles/idubu-akagara-divide-banyamulenge",
    excerpt: "A new generation of Banyamulenge is divided. On one side, the 'Idubu', who support the Twirwaneho militia. On the other, the 'Akagara', who advocate for cooperation with the government. This article explores the origins and implications of this division.",
    main_image_url: "https://picsum.photos/seed/banyamulenge-division/800/600",
    category: { name: "Conflict", href: "/category/conflict" },
    author_name: "Imuhira Staff",
    published_at: "3 hours ago",
    youtube_video_id: "dQw4w9WgXcQ",
  },
  {
    id: 202,
    title: "Life Under Siege: A Report from Minembwe",
    slug: "life-under-siege-minembwe",
    href: "/articles/life-under-siege-minembwe",
    excerpt: "For months, the town of Minembwe has been under siege, cut off from the rest of the world. This is a report from inside the besieged town, where the population is struggling to survive.",
    main_image_url: "https://picsum.photos/seed/minembwe-siege/800/600",
    category: { name: "Conflict", href: "/category/conflict" },
    author_name: "Imuhira Staff",
    published_at: "1 day ago",
    youtube_video_id: "dQw4w9WgXcQ",
  },

  // CULTURE
  {
    id: 301,
    title: "Inanga: The Sound of the Banyamulenge",
    slug: "inanga-sound-of-banyamulenge",
    href: "/articles/inanga-sound-of-banyamulenge",
    excerpt: "The inanga, a traditional stringed instrument, is at the heart of Banyamulenge culture. This article explores the history of the inanga and its role in Banyamulenge society.",
    main_image_url: "https://picsum.photos/seed/inanga/800/600",
    category: { name: "Culture", href: "/category/culture" },
    author_name: "Imuhira Staff",
    published_at: "4 hours ago",
    youtube_video_id: "dQw4w9WgXcQ",
  },
  {
    id: 302,
    title: "The Banyamulenge Diaspora: A Story of Exile and Resilience",
    slug: "banyamulenge-diaspora-exile-resilience",
    href: "/articles/banyamulenge-diaspora-exile-resilience",
    excerpt: "Forced to flee their homeland, the Banyamulenge diaspora has spread across the globe. This article tells the story of their exile and their efforts to preserve their culture and traditions.",
    main_image_url: "https://picsum.photos/seed/banyamulenge-diaspora/800/600",
    category: { name: "Culture", href: "/category/culture" },
    author_name: "Imuhira Staff",
    published_at: "8 hours ago",
    youtube_video_id: "dQw4w9WgXcQ",
  },

  // STORIES
  {
    id: 401,
    title: "My Father, the Mulao",
    slug: "my-father-the-mulao",
    href: "/articles/my-father-the-mulao",
    excerpt: "A personal story about growing up as the son of a Banyamulenge chief and the challenges of leadership in a time of conflict.",
    main_image_url: "https://picsum.photos/seed/mulao-story/800/600",
    category: { name: "Stories", href: "/category/stories" },
    author_name: "Gatete",
    published_at: "1 day ago",
    youtube_video_id: "dQw4w9WgXcQ",
  },
  {
    id: 402,
    title: "The Day the Cows Didn't Come Home",
    slug: "the-day-the-cows-didnt-come-home",
    href: "/articles/the-day-the-cows-didnt-come-home",
    excerpt: "A moving story about the impact of cattle raiding on a Banyamulenge family and their struggle to survive.",
    main_image_url: "https://picsum.photos/seed/cow-story/800/600",
    category: { name: "Stories", href: "/category/stories" },
    author_name: "Mabenga",
    published_at: "2 days ago",
    youtube_video_id: "dQw4w9WgXcQ",
  },
];
